document.addEventListener("DOMContentLoaded", function () {
    function FlightModel() {
        this.flights = {
            'Non stop': [
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '870 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '05/11/2019',
                    departureDateDays: 'In 6 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '03:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '870 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '570 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '660 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '370 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/nature',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '470 $'
                },
            ],
            'Best price': [
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '230 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '05/11/2019',
                    departureDateDays: 'In 6 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '03:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '110 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '330 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '440 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '370 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/people',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '430 $'
                },
            ],
            'Airline': [
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '235 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '05/11/2019',
                    departureDateDays: 'In 6 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '03:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '335 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '555 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '325 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '370 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/tech',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '430 $'
                },
            ],
            'Schedule': [
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '667 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '05/11/2019',
                    departureDateDays: 'In 6 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '03:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '445 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '666 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '440 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '370 $'
                },
                {
                    airlineIcon: 'https://placeimg.com/48/48/sepia',
                    airlineName: 'Delta',
                    airlineFlightNum: 'DL4051',
                    departureDate: '03/11/2019',
                    departureDateDays: 'In 3 days',
                    departureAirport: 'Paris (CDG)',
                    departureTime: '07:15',
                    arrivalCity: 'Miami',
                    arrivalTime: '10:15',
                    flightTime: '5:00',
                    flightChain: 'CDG - MIA',
                    flightPrice: '430 $'
                },
            ],
        };

        this.flightOrder = ko.observable('Non stop');

        this.chosenFlights = ko.observable(this.flights[this.flightOrder()]);

        this.setFlights = function (data, event) {
            let chosenFlightType = event.target.text;
            this.flightOrder(chosenFlightType);
            this.chosenFlights(this.flights[chosenFlightType]);
        };
    }

    ko.applyBindings(new FlightModel());
});
